#!/bin/bash

# Copyright (c) 2024 Ortus Solutions, Corp. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description:
# Launcher script for TestBox's BoxLang runner.
# It resolves this script's directory and executes:
#   system/runners/BoxLangRunner.bx
# passing through all CLI arguments unchanged.

# Get the path to the directory where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Go baby go!
boxlang $DIR/system/runners/BoxLangRunner.bx $@