# This workflow is used to build releases
# It can also be called by other workflows to reuse the release flow.
name: TestBox Release

on:
  push:
    branches:
      - master
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_ACCESS_SECRET:
        required: true
      FORGEBOX_API_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  build:
    name: Build & Publish Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_API_TOKEN }}

      - name: Setup Environment Variables For Build Process
        id: current_version
        run: |
          echo "TESTBOX_VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV
          box package set version=@build.version@+@build.number@
          # master or snapshot
          echo "Github Ref is $GITHUB_REF"
          echo "BRANCH=master" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/development' ]
          then
            echo "BRANCH=development" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        run: |
          box install --production

      - name: Build TestBox for ${{ env.BRANCH }} v${{ env.TESTBOX_VERSION }}
        run: |
          box install commandbox-docbox
          box task run taskfile=build/Build target=run :version=${{ env.TESTBOX_VERSION }} :buildID=${{ github.run_number }} :branch=${{ env.BRANCH }}

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: testbox
          path: |
            .artifacts/**/*

      - name: Upload Binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "downloads.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".artifacts"
          DEST_DIR: "ortussolutions"

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/apidocs"
          DEST_DIR: "testbox/${{ env.TESTBOX_VERSION }}"

      - name: Publish
        run: |
          cd .tmp/testbox
          cat box.json
          box forgebox publish

      - name: Inform Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testbox
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: 'TestBox ${{ env.TESTBOX_VERSION }} Built with ${{ job.status }}!'
          SLACK_TITLE: "TestBox Build"
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
