name: TestBox Snapshots

on:
  push:
    branches:
      - development

# Unique group name per workflow-branch/tag combo
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  format:
    name: Code Auto-Formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Auto-format
        uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes
          push_options: --force

  #############################################
  # Build Snapshot Release
  #############################################
  build:
    uses: ./.github/workflows/release.yml
    needs: [ tests, format ]
    secrets: inherit
    with:
      snapshot: true
